# Generated by Django 4.2.10 on 2025-04-26 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'blacklisted token',
                'verbose_name_plural': 'blacklisted tokens',
                'ordering': ['-blacklisted_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('auth_success', 'Successful Authentication'), ('auth_failure', 'Failed Authentication'), ('access_denied', 'Access Denied'), ('password_change', 'Password Changed'), ('email_change', 'Email Changed'), ('profile_update', 'Profile Updated'), ('role_change', 'Role Changed'), ('api_access', 'API Access'), ('sensitive_data', 'Sensitive Data Access'), ('otp_verify', 'OTP Verification'), ('lockout', 'Account Lockout'), ('suspicious', 'Suspicious Activity')], max_length=20)),
                ('event_description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security audit log',
                'verbose_name_plural': 'security audit logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.TextField()),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for permanent blacklisting', null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ip_blacklist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP blacklist',
                'verbose_name_plural': 'IP blacklists',
                'ordering': ['-blacklisted_at'],
            },
        ),
    ]
