# Generated by Django 4.2.10 on 2025-04-26 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_notifications', models.BooleanField(default=True)),
                ('security_notifications', models.BooleanField(default=True)),
                ('promotional_notifications', models.BooleanField(default=False)),
                ('info_notifications', models.BooleanField(default=True)),
                ('transaction_channel', models.CharField(choices=[('app', 'In-App Notification'), ('email', 'Email Notification'), ('sms', 'SMS Notification'), ('push', 'Push Notification')], default='app', max_length=10)),
                ('security_channel', models.CharField(choices=[('app', 'In-App Notification'), ('email', 'Email Notification'), ('sms', 'SMS Notification'), ('push', 'Push Notification')], default='app', max_length=10)),
                ('promotional_channel', models.CharField(choices=[('app', 'In-App Notification'), ('email', 'Email Notification'), ('sms', 'SMS Notification'), ('push', 'Push Notification')], default='app', max_length=10)),
                ('info_channel', models.CharField(choices=[('app', 'In-App Notification'), ('email', 'Email Notification'), ('sms', 'SMS Notification'), ('push', 'Push Notification')], default='app', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('transaction', 'Transaction Notification'), ('security', 'Security Alert'), ('promotion', 'Promotional Message'), ('info', 'General Information')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_read', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='URL for action button in notification', max_length=255)),
                ('action_text', models.CharField(blank=True, help_text='Text for action button in notification', max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of related object (transaction, etc.)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-important', '-date_created'],
            },
        ),
    ]
